### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by kpalmvik** [andrewjtimmons/bikelanes#1]
Hi @andrewjtimmons. I just forked the repo, but since there is no license information I am not sure what I am allowed to do with it.

My idea is to create a Swedish version of the page, including proper credit and link to you. Could you please clarify the licensing, perhaps by adding a LICENSE file, so I would know if I am allowed to do this?

**Comment by andrewjtimmons** [comment]
Hi Kpalmvik,

Thanks for the fork!

What you want to do sounds really cool.  I added the MIT license so you are definitely allowed to do your project.  Have fun!

Would love to see what you have when you are done. 

Cheers,
Andy

**Comment by kpalmvik** [comment]
Very cool, I appreciate it!
